// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

/*==========================================
 * CreativeSD: BattleGround Queue Expansive
 *------------------------------------------*/
	BUILDIN_DEF(bg_kick_team, "i"),
	BUILDIN_DEF(bg_team_size, "i"),
	BUILDIN_DEF(bg_get_team, "i"),
	BUILDIN_DEF(bg_set_respawn, "iii"),
	BUILDIN_DEF(bg_attach_respawn, "??"),
	BUILDIN_DEF(bg_attach_respawn_all, "i?"),
	BUILDIN_DEF(bg_viewpoint, "iiiiii"),
	BUILDIN_DEF(bg_team_getxy, "ii"),
	BUILDIN_DEF(bg_respawn_getxy, "ii"),
	BUILDIN_DEF(bg_areapercentheal, "isiiiiii"),
	BUILDIN_DEF(bg_refresh_patent, "i"),
	BUILDIN_DEF(bg_message, "is"),
	BUILDIN_DEF(bg_digit_timer, "i?"),
	BUILDIN_DEF(bg_console, "s"),