// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

/*==========================================
 * CreativeSD: BattleGround Queue Expansive
 *------------------------------------------*/
		ACMD_DEF(reloadbg),
		ACMD_DEF(bgregister),
		ACMD_DEF(bgjoin),
		ACMD_DEF(bgleave),
		ACMD_DEF(bgunregister),
		ACMD_DEF(bgreportafk),
		ACMD_DEF(bgwaiting),
		ACMD_DEF2("bgplaying", bgwaiting),
		ACMD_DEF(bgranking),
		ACMD_DEF(bgorder),
		ACMD_DEF(bgchangeleader),