// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

/*==========================================
 * CreativeSD: Queue System
 *------------------------------------------*/
	BUILDIN_DEF(queue_create, "is?"),
	BUILDIN_DEF(queue_delete, "i"),
	BUILDIN_DEF(queue_change, "iis"),
	BUILDIN_DEF(queue_check, "i"),
	BUILDIN_DEF(queue_size, "i"),
	BUILDIN_DEF(queue_join, "i???"),
	BUILDIN_DEF(queue_leave, "??"),
	BUILDIN_DEF(queue_clean, "i??"),
	BUILDIN_DEF(queue_get_players, "i"),
	BUILDIN_DEF(queue_get_data, "ii"),
	BUILDIN_DEF(queue_char_info, "i?"),
	BUILDIN_DEF(queue_set_delay, "i?"),