// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

		/*==========================================
		 * CreativeSD: Queue System
		 *------------------------------------------*/
		ACMD_DEF(queue),
		ACMD_DEF(queuelist),
		ACMD_DEF(queuekick),
		ACMD_DEF(queuesetdelay),
		ACMD_DEF(queuedelay),
		ACMD_DEF(queuenomove),